# Generated by Django 5.0.1 on 2024-05-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicapp', '0002_alter_post_posteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='event_news')),
                ('description', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=50)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
    ]
