# Generated by Django 5.0.1 on 2024-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(default='general', max_length=200)),
            ],
        ),
    ]
