<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-03-02 13:39

import django.db.models.deletion
=======
# Generated by Django 4.2.3 on 2023-11-22 09:40

>>>>>>> 1c239607f22fe8c0decd8b5d29d10a429c48233f
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(default='general', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profilepics')),
                ('reward', models.IntegerField(default=0)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='generalapp.user')),
                ('followings', models.ManyToManyField(blank=True, related_name='followings', to='generalapp.user')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalapp.user')),
=======
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contactno', models.IntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
>>>>>>> 1c239607f22fe8c0decd8b5d29d10a429c48233f
            ],
        ),
    ]
