# Generated by Django 5.0.1 on 2024-03-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('postcaption', models.TextField()),
                ('postimage', models.ImageField(blank=True, upload_to='posts')),
                ('posteddate', models.CharField(max_length=30)),
                ('postedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalapp.user')),
            ],
        ),
    ]
