# Generated by Django 5.0.1 on 2024-03-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
