# Generated by Django 5.0.1 on 2024-05-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_msg', models.TextField()),
                ('notification_by', models.CharField(max_length=200)),
                ('notification_to', models.CharField(max_length=200)),
                ('notification_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profilepics')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='generalapp.user')),
                ('followings', models.ManyToManyField(blank=True, related_name='followings', to='generalapp.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('postcaption', models.TextField()),
                ('postimage', models.ImageField(blank=True, upload_to='posts')),
                ('posteddate', models.CharField(max_length=30)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='generalapp.user')),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('j_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_required', models.TextField()),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('job_location', models.CharField(max_length=500)),
                ('job_post_date', models.DateField()),
                ('job_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, upload_to='donate_products')),
                ('donar_location', models.CharField(max_length=300)),
                ('rewards', models.ManyToManyField(blank=True, related_name='rewards', to='generalapp.user')),
                ('donated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('complain_image', models.ImageField(blank=True, upload_to='complain_images')),
                ('complain_location', models.CharField(max_length=300)),
                ('complain_status', models.CharField(default='unsolved', max_length=100)),
                ('complain_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TopEnvorior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
    ]
