# Generated by Django 5.0.1 on 2024-03-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0001_initial'),
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('postcaption', models.TextField()),
                ('postimage', models.ImageField(blank=True, upload_to='posts')),
                ('posteddate', models.CharField(max_length=30)),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
                ('reward', models.ManyToManyField(blank=True, related_name='reward', to='generalapp.user')),
            ],
        ),
    ]
