# Generated by Django 5.0.1 on 2024-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_msg', models.TextField()),
                ('notification_by', models.CharField(max_length=200)),
                ('notification_to', models.CharField(max_length=200)),
                ('notification_date', models.DateField()),
            ],
        ),
    ]
