# Generated by Django 5.0.1 on 2024-03-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, upload_to='donate_products')),
                ('donar_location', models.CharField(max_length=300)),
                ('donated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
    ]
