# Generated by Django 5.0.1 on 2024-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0009_complain_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
