# Generated by Django 5.0.1 on 2024-03-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0001_initial'),
        ('publicapp', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reward',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='generalapp.user'),
        ),
    ]
