# Generated by Django 5.0.1 on 2024-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0002_alter_post_postedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedby',
            field=models.CharField(max_length=200),
        ),
    ]
