# Generated by Django 5.0.1 on 2024-03-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0003_remove_post_reward_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('j_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_required', models.TextField()),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('job_location', models.CharField(max_length=500)),
                ('job_post_date', models.DateField()),
                ('job_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
    ]
