# Generated by Django 5.0.1 on 2024-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0004_remove_profile_followers_remove_profile_followings_and_more'),
        ('publicapp', '0004_remove_profile_reward_profile_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reward',
        ),
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.ManyToManyField(blank=True, related_name='reward', to='generalapp.user'),
        ),
    ]
