# Generated by Django 5.0.1 on 2024-03-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0006_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('complain_image', models.ImageField(blank=True, upload_to='complain_images')),
                ('complain_location', models.CharField(max_length=300)),
                ('complain_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
    ]
