# Generated by Django 5.0.1 on 2024-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0006_rename_postedby_post_postby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reward',
        ),
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
