# Generated by Django 5.0.1 on 2024-03-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0007_remove_post_reward_post_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.FileField(blank=True, upload_to='posts'),
        ),
    ]
