# Generated by Django 5.0.1 on 2024-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0008_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
