# Generated by Django 5.0.1 on 2024-03-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0008_topenvorior'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_status',
            field=models.CharField(default='unsolved', max_length=100),
        ),
    ]
