# Generated by Django 5.0.1 on 2024-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0009_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
