# Generated by Django 5.0.1 on 2024-04-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0001_initial'),
        ('publicapp', '0010_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='rewards', to='generalapp.user'),
        ),
    ]
