# Generated by Django 5.0.1 on 2024-03-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0011_alter_post_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('j_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('job_location', models.CharField(max_length=500)),
                ('job_by', models.CharField(max_length=500)),
                ('job_post_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_msg', models.TextField()),
                ('notification_by', models.CharField(max_length=200)),
                ('notification_to', models.CharField(max_length=200)),
                ('notification_date', models.DateField()),
            ],
        ),
    ]
