# Generated by Django 5.0.1 on 2024-03-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0012_job_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill_required',
            field=models.TextField(default=0.0005931784478497281),
            preserve_default=False,
        ),
    ]
