# Generated by Django 5.0.1 on 2024-03-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0015_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaiton',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_to', models.CharField(max_length=300)),
                ('notification_msg', models.TextField()),
                ('notification_date', models.DateField()),
                ('notification_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.profile')),
            ],
        ),
    ]
