# Generated by Django 5.0.1 on 2024-03-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0004_remove_profile_followers_remove_profile_followings_and_more'),
        ('publicapp', '0016_notificaiton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalapp.user'),
        ),
    ]
